import bpy
import math

# --- SCRIPT 2 of 2: GENERATE ANIMATIONS --- 
# This script's only job is to create the animation data for the hand poses.
# It exports a file containing ONLY the animation data, which will be applied
# to the clean base model generated by the first script.

def clear_scene():
    """Wipes the scene clean."""
    if bpy.context.active_object and bpy.context.active_object.mode != 'OBJECT':
        bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete()

def create_single_rigged_hand(side_prefix):
    """Creates one complete, rigged hand object."""
    x_mult = 1 if side_prefix == 'R' else -1
    parts = []
    
    bpy.ops.mesh.primitive_cube_add(location=(0, 0, 0)); palm = bpy.context.active_object
    palm.name = f"Palm.{side_prefix}"; palm.scale = (0.7, 1, 0.2); parts.append(palm)
    
    finger_mesh_data = [("Index", (-0.35, 0.85, 0), (0.18, 0.7, 0.18)), ("Middle", (-0.1, 0.9, 0), (0.2, 0.8, 0.2)), ("Ring", (0.15, 0.87, 0), (0.18, 0.75, 0.18)), ("Pinky", (0.4, 0.8, 0), (0.15, 0.6, 0.15))]
    for name, loc, scale in finger_mesh_data:
        bpy.ops.mesh.primitive_cube_add(location=(loc[0] * x_mult, loc[1], loc[2])); finger = bpy.context.active_object
        finger.name = f"{name}.{side_prefix}"; finger.scale = scale; parts.append(finger)
        
    bpy.ops.mesh.primitive_cube_add(location=(-0.6 * x_mult, 0.3, 0)); thumb = bpy.context.active_object
    thumb.name = f"Thumb.{side_prefix}"; thumb.scale = (0.2, 0.4, 0.2); parts.append(thumb)
    
    for part in parts:
        bpy.context.view_layer.objects.active = part
        bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
        
    bpy.ops.object.armature_add(enter_editmode=True, align='WORLD', location=(0,0,0)); armature = bpy.context.active_object
    armature.name = f"Armature.{side_prefix}"; edit_bones = armature.data.edit_bones
    palm_bone = edit_bones.get('Bone'); palm_bone.name = "Palm"; palm_bone.head, palm_bone.tail = (0, -0.5, 0), (0, 0.5, 0)
    
    finger_bone_data = [("Index", (-0.35, 0.5, 0), 0.35), ("Middle", (-0.1, 0.5, 0), 0.4), ("Ring", (0.15, 0.5, 0), 0.38), ("Pinky", (0.4, 0.5, 0), 0.3)]
    for name, pos, length in finger_bone_data:
        bone1 = edit_bones.new(f'{name}1'); bone1.head, bone1.tail = (pos[0]*x_mult, pos[1], 0), (pos[0]*x_mult, pos[1] + length, 0); bone1.parent = palm_bone
        bone2 = edit_bones.new(f'{name}2'); bone2.head, bone2.tail = (pos[0]*x_mult, pos[1] + length, 0), (pos[0]*x_mult, pos[1] + length * 2, 0); bone2.parent = bone1
        
    thumb1 = edit_bones.new('Thumb1'); thumb1.head, thumb1.tail = ((-0.6*x_mult, 0.2, 0), (-0.8*x_mult, 0.6, 0)); thumb1.parent = palm_bone
    bpy.ops.object.mode_set(mode='OBJECT')
    
    bpy.ops.object.select_all(action='DESELECT')
    for p in parts:
        p.select_set(True)
    bpy.context.view_layer.objects.active = palm
    bpy.ops.object.join()
    hand_mesh = bpy.context.active_object
    hand_mesh.name = f"Hand_Mesh.{side_prefix}"

    bpy.ops.object.modifier_add(type='SUBSURF'); hand_mesh.modifiers["Subdivision"].levels = 2

    bpy.ops.object.select_all(action='DESELECT')
    hand_mesh.select_set(True)
    armature.select_set(True)
    bpy.context.view_layer.objects.active = armature
    bpy.ops.object.parent_set(type='ARMATURE_AUTO')

    return armature

def set_and_keyframe_pose(armature, frame, pose_data):
    bpy.context.scene.frame_set(frame)
    bpy.context.view_layer.objects.active = armature
    bpy.ops.object.mode_set(mode='POSE')
    for bone_name, (x, y, z) in pose_data.items():
        bone = armature.pose.bones.get(bone_name)
        if bone:
            bone.rotation_mode = 'XYZ'
            bone.rotation_euler.x = math.radians(x)
            bone.rotation_euler.y = math.radians(y)
            bone.rotation_euler.z = math.radians(z)
            bone.keyframe_insert(data_path="rotation_euler", index=-1)

def main():
    """Main function to create and export the hand animations."""
    clear_scene()

    right_armature = create_single_rigged_hand('R')
    left_armature = create_single_rigged_hand('L')

    pose_open_r = {"Palm": (0, -75, -20), "Thumb1": (10, 45, -105), "Index1": (0, 0, -15), "Index2": (0,0,0), "Middle1": (0,0,0), "Middle2": (0,0,0), "Ring1": (0, 0, 15), "Ring2": (0,0,0), "Pinky1": (0, 0, 45), "Pinky2": (0, 0, -20)}
    pose_open_l = {"Palm": (0, 75, 20), "Thumb1": (10, -45, 105), "Index1": (0, 0, 15), "Index2": (0,0,0), "Middle1": (0,0,0), "Middle2": (0,0,0), "Ring1": (0, 0, -15), "Ring2": (0,0,0), "Pinky1": (0, 0, -45), "Pinky2": (0, 0, 20)}
    pose_catch_r = {"Palm": (0, -75, -20), "Thumb1": (13, 45, -105), "Index1": (85, 0, -15), "Index2": (90, 0, 0), "Middle1": (85, 0, 0), "Middle2": (90, 0, 0), "Ring1": (85, 0, 15), "Ring2": (90, 0, 0), "Pinky1": (85, 0, 45), "Pinky2": (90, 0, -20)}
    pose_catch_l = {"Palm": (0, 75, 20), "Thumb1": (13, -45, 105), "Index1": (85, 0, 15), "Index2": (90, 0, 0), "Middle1": (85, 0, 0), "Middle2": (90, 0, 0), "Ring1": (85, 0, -15), "Ring2": (90, 0, 0), "Pinky1": (85, 0, -45), "Pinky2": (90, 0, 20)}

    def create_action_for_pose(armature, action_name, pose_data):
        action = bpy.data.actions.new(name=action_name)
        if not armature.animation_data:
            armature.animation_data_create()
        armature.animation_data.action = action
        set_and_keyframe_pose(armature, 1, pose_data)
        track = armature.animation_data.nla_tracks.new()
        track.name = action_name
        track.strips.new(name=action_name, start=1, action=action)

    create_action_for_pose(right_armature, "Pose-Catch.R", pose_catch_r)
    create_action_for_pose(right_armature, "Pose-Open.R", pose_open_r)
    create_action_for_pose(left_armature, "Pose-Catch.L", pose_catch_l)
    create_action_for_pose(left_armature, "Pose-Open.L", pose_open_l)

    filepath = "D:\\catch-game\\assets\\hands_animations.glb"
    bpy.ops.export_scene.gltf(
        filepath=filepath,
        use_selection=False,
        export_apply=True,
        export_animations=True,
        export_nla_strips=True,
        export_rest_position_armature=True
    )

    print(f"--- SCRIPT FINISHED ---\nExported animation data to {filepath}")

main()
